-- 1. Infrastructure Setup
CREATE DATABASE IF NOT EXISTS WEATHER_DB;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.RAW;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.BRONZE;

-- اضافه کردن Stage داخلی برای مدیریت فایل‌های JSON
CREATE STAGE IF NOT EXISTS WEATHER_DB.RAW.MY_INTERNAL_STAGE
    FILE_FORMAT = (TYPE = 'JSON');

-- 2. RAW Layer Tables (Persistent Landing Zone)
CREATE TABLE IF NOT EXISTS WEATHER_DB.RAW.RAW_WEATHER_DATA_COMPLEX (
    JSON_DATA VARIANT,
    INGESTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS WEATHER_DB.RAW.RAW_AIR_QUALITY_COMPLEX (
    JSON_DATA VARIANT,
    INGESTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. BRONZE Layer Tables (Clean & Structured Data)
CREATE TABLE IF NOT EXISTS WEATHER_DB.BRONZE.BRONZE_WEATHER (
    RECORD_ID NUMBER,
    CITY STRING,
    TEMPERATURE_C FLOAT,
    HUMIDITY_PCT NUMBER,
    DATA_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_SYSTEM STRING,
    PRODUCER_ID STRING,
    LOAD_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS WEATHER_DB.BRONZE.BRONZE_AIR_QUALITY (
    RECORD_ID NUMBER,
    CITY STRING,
    AQI_INDEX NUMBER,
    PM25 FLOAT,
    SENSOR_STATUS STRING,
    DATA_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_SYSTEM STRING,
    PRODUCER_ID STRING,
    LOAD_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. Change Data Capture (Streams)
-- Streams allow us to track only NEW records in the RAW tables
CREATE STREAM IF NOT EXISTS WEATHER_DB.RAW.RAW_WEATHER_STREAM 
    ON TABLE WEATHER_DB.RAW.RAW_WEATHER_DATA_COMPLEX;

CREATE STREAM IF NOT EXISTS WEATHER_DB.RAW.RAW_AIR_QUALITY_STREAM 
    ON TABLE WEATHER_DB.RAW.RAW_AIR_QUALITY_COMPLEX;